CREATE TABLE orders (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    order_id VARCHAR(50) UNIQUE NOT NULL,
    kite_order_id VARCHAR(50),
    user_id BIGINT NOT NULL,
    stock_id BIGINT NOT NULL,
    transaction_type ENUM('BUY', 'SELL') NOT NULL,
    order_type ENUM('MARKET', 'LIMIT', 'SL', 'SL_M') NOT NULL,
    quantity INT NOT NULL,
    price DECIMAL(10,2),
    executed_price DECIMAL(10,2),
    executed_quantity INT DEFAULT 0,
    status ENUM('PENDING', 'OPEN', 'PARTIAL', 'COMPLETE', 'CANCELLED', 'REJECTED') DEFAULT 'PENDING',
    validity VARCHAR(10) DEFAULT 'DAY',
    disclosed_quantity INT,
    trigger_price DECIMAL(10,2),
    notes VARCHAR(500),
    rejection_reason VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    executed_at TIMESTAMP NULL,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (stock_id) REFERENCES stocks(id),
    INDEX idx_order_id (order_id),
    INDEX idx_kite_order_id (kite_order_id),
    INDEX idx_user_id (user_id),
    INDEX idx_stock_id (stock_id),
    INDEX idx_status (status),
    INDEX idx_created_at (created_at)
);